# Generated by Django 3.1.1 on 2020-09-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_stories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(),
        ),
    ]
