# Generated by Django 3.1.1 on 2020-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200904_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
